language: go

sudo: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

go:
  - 1.5
  - 1.6
  - tip

services:
  - postgresql

env:
  global:
    - POSTGRES_HOST=127.0.0.1:5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=""
    - POSTGRES_DB=travis_ci_test
    - PORT=8080

install:
  - glide install -s

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go test -v
