language: go

sudo: required

go:
  - 1.6
  - tip

services:
  - postgresql

addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
  postgresql: 9.5

env:
  global:
    - PGPORT=5433
    - PGHOST=localhost
    - GO15VENDOREXPERIMENT=1
    - POSTGRES_HOST=127.0.0.1:5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=""
    - POSTGRES_DB=travis_ci_test

install: true

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go test -v
