language: go

go:
  - 1.5
  - 1.6
  - tip

services:
  - postgresql

env:
  - >
    GO15VENDOREXPERIMENT=1
    POSTGRES_HOST=127.0.0.1:5432
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=""
    POSTGRES_DB=travis_ci_test

install: true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go test -v
