FROM scratch
ADD bin/goweb /goweb

ENV POSTGRES_HOST ${POSTGRES_HOST}
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}

ENV PORT 8080
EXPOSE ${PORT}

CMD ["/goweb"]
