version: '2'
services:

  go: &go
    image: golang
    working_dir: /go/src/github.com/gnhuy91/goweb
    volumes:
      - .:/go/src/github.com/gnhuy91/goweb
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db

  go-test:
    <<: *go
    command: go test -v

  go-build:
    <<: *go
    command: sh -c 'rm -f bin/goweb && go build -o bin/goweb'
    environment:
      CGO_ENABLED: 0

  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
